import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./cart/cart-context"

export const metadata: Metadata = {
  title: "Zenith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
