import UserTemplate from "@/components/cashierTemplate"
import MenuListCashier from "../menuListCashier"

export const metadata = {
    title: 'Dashboard | FOS',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <UserTemplate title="Dashboard" id="dashboard"
            menuList={MenuListCashier}>
            {children}
        </UserTemplate>
    )
}
export default RootLayout