import UserTemplate from "@/components/cashierTemplate"
import MenuListCashier from "../menuListCashier"

export const metadata = {
    title: 'Transaksi | FOS',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <UserTemplate title="Transaksi" id="transaksi"
            menuList={MenuListCashier}>
            {children}
        </UserTemplate>
    )
}
export default RootLayout